### ISSUE TITLE
Create an .env file and add the environment variable for keys.

### ISSUE THREAD

**Issue by khuzama98** [XORD-one/nestJS-boilerplate#6]
So far the below modules needs to be connected through the environment variables for the keys.

**Keys:**

- Stripe key
- Paypal Key
- Karaken
- MongoDB
- Nodemailer(all auth keys)

**Comment by umer2001** [comment]
Hey,
can I help?
if yes, please assign me the issue.

**Comment by khuzama98** [comment]
okay great, I'm assigning it to you @umer2001

**Comment by umer2001** [comment]
@khuzama98  You can check above pull request that I submitted before you assign me the issue.
